### ISSUE TITLE
Compilation error - treeN.h: No such file or directory

### ISSUE THREAD

**Issue by naturepoker** [rcedgar/newick#2]
Running the make command within cloned repo /src directory returns below error:

```
g++  -DNDEBUG -pthread  -O3 -fopenmp -ffast-math -msse -mfpmath=sse -c -o o/relabel.o relabel.cpp
relabel.cpp:2:10: fatal error: treeN.h: No such file or directory
    2 | #include "treeN.h"
      |          ^~~~~~~~~
compilation terminated.
make: *** [Makefile:154: o/relabel.o] Error 1
```

Granted, there's a binary available directly on the front page, but I'd love to be able to compile this myself for study's sake. 
Copying the noted treen.h file into usr/include on my system doesn't seem to change anything. 

My system is Ubuntu 22.04.3 LTS running system default g++

Thank you!

**Comment by rcedgar** [comment]
`treen.h` is already in the repo, you should be able to fix this by changing `treeN.h` to `treen.h ` in `relabel.cpp` (unfortunately I missed this problem because I tested on a file system which is case-insensitive)

**Comment by naturepoker** [comment]
Changing treeN.h to treen.h in the .cpp file as you instructed fixed everything. The binary seems to be working perfectly. 

Thank you very much for the quick response and, of course, the hard work maintaining the program! I'll close this issue.
