### ISSUE TITLE
subtree command

### ISSUE THREAD

**Issue by carolynzy** [rcedgar/newick#4]
Hi, 

I want to use the subtree command, but when I use the following command line:

`newick -input NP_214621.nwk.txt -labels labels.txt -output NP_214621_subtree.nwk`

it gives me this error message:

```
Invalid command line
Unknown option input
```

so I guess it might should be like this :

`newick -subtree NP_214621.nwk.txt -labels labels.txt -output NP_214621_subtree.nwk`

this time it gave me more information but still failed:

```
newick v1.0.1429_i86linux64, 16.3Gb RAM, 12 cores

newick 1.0.1429_i86linux64  16.3Gb RAM, 12 cores
(C) Copyright 2020-21 Robert C. Edgar, all rights reserved.
https://drive5.com



newick -subtree NP_214621.nwk.txt -labels labels.txt -output NP_214621_subtree.nwk
Elapsed time 00:00
Max memory 0.0b

---Fatal error---
Not implemented
```

Any idea what went wrong?  Please kindly help me out. 

Yang

**Comment by rcedgar** [comment]
There is no command called subtree.

**Comment by carolynzy** [comment]
Yes, in the manual there is no subtree. Then how should I use the function to make a subtree? The command line in the manual doesn't work for me.

**Comment by rcedgar** [comment]
The C++ source code for manipulating trees is available in the github repository if you want to try modifying the code to meet your needs, but the source code as such is not designed to be used by anyone except me and is not documented.

**Comment by carolynzy** [comment]
I have no experience of C++. It's a pity that subtree function doesn't work for me. I find this program quite handy.  Thank you for sharing it.
